name: Android CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleRelease

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: Release Apk
          path: app/build/outputs